export const SAVE_PREPARE_CAMPAIGN = "SAVE_PREPARE_CAMPAIGN";
export const SAVE_PREPARE_CAMPAIGN_SAGA = "SAVE_PREPARE_CAMPAIGN_SAGA";
export const ADD_CAMPAIGN = "ADD_CAMPAIGN";
export const ADD_CAMPAIGN_SAGA = "ADD_CAMPAIGN_SAGA";
export const SET_STEP_TYPE = "SET_STEP_TYPE";
